In [24]:
import numpy as np
from scipy.spatial.transform import Rotation

m = 60
X = np.zeros((m, 3))  # initialize 3D dataset
np.random.seed(42)
angles = (np.random.rand(m) ** 3 + 0.5) * 2 * np.pi  # uneven distribution
X[:, 0], X[:, 1] = np.cos(angles), np.sin(angles) * 0.5  # oval
X += 0.28 * np.random.randn(m, 3)  # add more noise
X = Rotation.from_rotvec([np.pi / 29, -np.pi / 20, np.pi / 4]).apply(X)
X += [0.2, 0, 0.2]  # shift a bit

In [25]:
X_centered = X - X.mean(axis=0)

U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt[0]
c2 = Vt[1]
print(f'c1: {c1}')
print(f'c2: {c2}')

c1: [0.67857588 0.70073508 0.22023881]
c2: [-0.72817329  0.6811147   0.07646185]


c1 and c2 are unit vector for each of the pricpal components for the 3D dataset

This can then be projected onto a hyperplane to tranform it to 2D space or d-space


In [26]:
W2 = Vt[:2].T
X2D = X_centered @ W2
print(f'old shape: {X_centered.shape}')
print(f'new shape: {X2D.shape}')

old shape: (60, 3)
new shape: (60, 2)


In [27]:
#With sklearn
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
print(f'first 5 rows without sklearn:\n {X2D[:5,:]}')
X2D = pca.fit_transform(X_centered)
print(f'first 5 rows with sklearn:\n {X2D[:5,:]}')

first 5 rows without sklearn:
 [[-0.87323119 -0.29459803]
 [ 0.14888518  0.51493557]
 [ 1.35121872 -0.39950155]
 [ 0.45436676 -0.1399845 ]
 [-0.73438909 -0.02289346]]
first 5 rows with sklearn:
 [[-0.87323119  0.29459803]
 [ 0.14888518 -0.51493557]
 [ 1.35121872  0.39950155]
 [ 0.45436676  0.1399845 ]
 [-0.73438909  0.02289346]]


In [28]:
pca.components_

array([[ 0.67857588,  0.70073508,  0.22023881],
       [ 0.72817329, -0.6811147 , -0.07646185]])

In [31]:
pca.explained_variance_ratio_

array([0.7578477 , 0.15186921])

In [32]:
from sklearn.datasets import fetch_openml

mnist = fetch_openml('mnist_784', as_frame=False)
X_train, X_test = mnist.data[:60000], mnist.data[60_000:]
y_train, y_test = mnist.target[:60000], mnist.target[60000:]

In [34]:
pca = PCA()
pca.fit(X_train)
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1
d

154

In [40]:
pca = PCA(n_components=0.95)
X_reduced = pca.fit_transform(X_train)

In [42]:
pca.n_components_

154